NFS Export operations support for NFS for powerflex v4.0
dell/goscaleio pull request #55
Opened 2023-04-18 15:14 UTC by KshitijaKakde

# Description
This PR includes changes for adding operation for NFS export for PowerFlex storage system v4.0

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| dell/csm#763

# Checklist:

- [X] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [X] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

Unit Test:
<img width="325" alt="integration_test" src="https://user-images.githubusercontent.com/111420075/232822456-f6ea4551-0c98-4cff-b2ec-c315bedf1f87.PNG">

2023-04-19 09:39 UTC, khareRajshree requested changes
@KshitijaKakde, please rebase this branch with main as I see a couple of changes not reflexting here since the last merge.

Also fix the linting errors reported from github workflow.

2023-04-19 09:48 UTC, khareRajshree requested changes
@KshitijaKakde Please address the below review comments. Thanks.

2023-04-19 09:48 UTC, khareRajshree commented on inttests/nfs_export_test.go
> +	fmt.Printf("filesystems[0].Name: %v", nfsexport[0].Name)
Please remove this print statement from integrations test.

2023-04-19 09:48 UTC, khareRajshree commented on inttests/nfs_export_test.go
> +// func TestGetFileSystemByName(t *testing.T) {
Please remove the commented code.

2023-04-19 09:48 UTC, khareRajshree commented on inttests/nfs_export_test.go
> +	// system := getSystem()
Please remove the commented code.

2023-04-19 09:48 UTC, khareRajshree commented on inttests/nfs_export_test.go
> +	nfsmodify := "NFS export modify testing"
Please remove this print statement from integrations test.

2023-04-19 09:48 UTC, khareRajshree commented on nfs_export.go
> +
Please remove this new line..

2023-04-19 10:08 UTC, khareRajshree commented on inttests/GOSCALEIO_TEST.env_example
> +GOSCALEIO_FILESYSTEM_NFSEXPORT=twee-fs11
please put a generic dummy value for GOSCALEIO_FILESYSTEM_NFSEXPORT

2023-04-19 10:10 UTC, khareRajshree requested changes
for the UTs and in-tests, please update with the latest results covering for all methods.

2023-04-20 04:51 UTC, ashleyvjoy approved these changes

2023-04-20 05:20 UTC, khareRajshree approved these changes

2023-04-21 08:18 UTC, VamsiSiddu-7 requested changes
@KshitijaKakde I have added some review comments. Please address those.

2023-04-21 08:18 UTC, VamsiSiddu-7 commented on types/v1/types.go
> +	Name         string `json:"name"`
add the required field to the name id and path

2023-04-21 08:18 UTC, VamsiSiddu-7 commented on types/v1/types.go
> +type CreateResponse struct {
can you rename this to NFSExportCreateResponse

2023-04-21 08:18 UTC, VamsiSiddu-7 commented on types/v1/types.go
> +	FileSystemID       string                     `json:"file_system_id,omitempty"`
if you dont provide the `json:` tag it cannot parse the id.

2023-04-21 14:56 UTC, merged