Pflex Tree quotas
dell/goscaleio pull request #70
Opened 2023-07-16 18:58 UTC by KshitijaKakde

# Description
This PR adds tree quota support for powerflex

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2023-07-20 09:56 UTC, khareRajshree requested changes

2023-07-20 09:56 UTC, khareRajshree commented on tree_quota.go
> +package goscaleio
Please add the copyright section for this file.

2023-07-20 19:24 UTC, khareRajshree commented on types/v1/types.go
> +	GracePeroid         int    `json:"grace_period,omitempty"`
typo --> "GracePeriod". Also check if any related instance needs to be updated.

2023-07-20 19:24 UTC, khareRajshree commented on types/v1/types.go
> +	GracePeroid          int    `json:"grace_period,omitempty"`
typo --> "GracePeriod"

2023-07-20 19:24 UTC, khareRajshree commented on types/v1/types.go
> +	GracePeroid          int    `json:"grace_period,omitempty"`
typo --> "GracePeriod"

2023-07-21 04:57 UTC, khareRajshree approved these changes

2023-07-21 05:54 UTC, ashleyvjoy approved these changes

2023-07-21 05:55 UTC, merged