Adding faultset support in sds and getting node/nodepool details
dell/goscaleio pull request #94
Opened 2024-01-17 18:39 UTC by shenda1

# Description
A few sentences describing the overall goals of the pull request's commits.

# GitHub Issues
List the GitHub issues impacted by this PR:

| GitHub Issue # |
| -------------- |
| |

# Checklist:

- [ ] I have performed a self-review of my own code to ensure there are no formatting, vetting, linting, or security issues
- [ ] I have verified that new and existing unit tests pass locally with my changes
- [ ] I have not allowed coverage numbers to degenerate
- [ ] I have maintained at least 90% code coverage
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Backward compatibility is not broken

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

2024-01-18 03:19 UTC, AkshaySainiDell requested changes

2024-01-18 03:19 UTC, AkshaySainiDell commented on inttests/node_test.go
> +// Copyright © 2021 - 2022 Dell Inc. or its subsidiaries. All Rights Reserved.
Copyright year should be `Copyright © 2024`

2024-01-18 03:19 UTC, AkshaySainiDell commented on node.go
Copyright info is missing for this file.

2024-01-18 03:19 UTC, AkshaySainiDell commented on node_test.go
Copyright info is missing for this file.

2024-01-18 03:19 UTC, AkshaySainiDell commented on sds.go
Update copyright year `Copyright © 2019 - 2024`

2024-01-18 03:19 UTC, AkshaySainiDell commented on types/v1/nodeTypes.go
Copyright info is missing for this file.

2024-01-18 03:25 UTC, AkshaySainiDell requested changes

2024-01-18 03:25 UTC, AkshaySainiDell commented on inttests/node_test.go
Can we have integration test for `GetNodePoolByID`?

2024-01-18 03:25 UTC, AkshaySainiDell commented on node_test.go
Is it possible to add UT for `GetNodeByFilters` ?

2024-01-18 09:56 UTC, AkshaySainiDell commented
@shenda1 could you please attach the code coverage ?

2024-01-18 11:03 UTC, shenda1 commented
> @shenda1 could you please attach the code coverage ?

@ Please find below unit tests coverage

![image](https://github.com/dell/goscaleio/assets/60608990/29034265-6f45-4e1e-af4a-b8d43776d30e)

2024-01-22 06:29 UTC, AkshaySainiDell approved these changes

2024-01-22 06:49 UTC, AnikaAgiwal2711 approved these changes

2024-01-22 06:49 UTC, merged